"use strict";
// ------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
// ------------------------------------------------------------------------------
Object.defineProperty(exports, "__esModule", { value: true });
var EnglishOptions;
(function (EnglishOptions) {
    EnglishOptions.LangMarker = 'Eng';
    EnglishOptions.TokenizerRegex = `[^\\w\\d]`;
    EnglishOptions.TrueRegex = `\\b(true|yes|yep|y|sure|ok|\\uD83D\\uDC4D|\\uD83D\\uDC4C)\\b`;
    EnglishOptions.FalseRegex = `\\b(false|nope|nop|no|\\uD83D\\uDC4E|\\u270B|\\uD83D\\uDD90)\\b`;
})(EnglishOptions = exports.EnglishOptions || (exports.EnglishOptions = {}));
//# sourceMappingURL=englishOptions.js.map